// Code generated by go-DDS IDL compiler. DO NOT EDIT.

package idlgen

import (
	"fmt"

	dds "github.com/SoundMatt/go-DDS"
	"github.com/SoundMatt/go-DDS/tools/cdr"
)

// _ suppresses unused-import errors in modules with no structs.
var _ = fmt.Sprintf
var _ = dds.DefaultQoS

// TopicID is a type alias generated from IDL typedef TopicID.
type TopicID = uint32

// Priority is generated from IDL enum Priority.
type Priority int32

const (
	PriorityLOW      Priority = 0
	PriorityMEDIUM   Priority = 1
	PriorityHIGH     Priority = 2
	PriorityCRITICAL Priority = 3
)

// Header is generated from IDL struct Header.
type Header struct {
	TopicId     string   `json:"topic_id"`
	TimestampNs int64    `json:"timestamp_ns"`
	Priority    Priority `json:"priority"`
}

// HeaderCodec encodes Header values using CDR/XCDR1.
type HeaderCodec struct{}

func (HeaderCodec) Marshal(v Header) ([]byte, error) {
	e := cdr.NewEncoder()
	e.WriteString(v.TopicId)
	e.WriteInt64(v.TimestampNs)
	e.WriteInt32(int32(v.Priority))
	return e.Bytes(), nil
}

func (HeaderCodec) Unmarshal(data []byte) (Header, error) {
	d, err := cdr.NewDecoder(data)
	if err != nil {
		return Header{}, fmt.Errorf("HeaderCodec: %w", err)
	}
	var v Header
	if v.TopicId, err = d.ReadString(); err != nil {
		return v, err
	}
	if v.TimestampNs, err = d.ReadInt64(); err != nil {
		return v, err
	}
	{
		var _ev int32
		if _ev, err = d.ReadInt32(); err != nil {
			return v, err
		}
		v.Priority = Priority(_ev)
	}
	return v, nil
}

// KeyFields returns the exported field names marked @key in the IDL source.
func (HeaderCodec) KeyFields() []string {
	return []string{"TopicId"}
}

// NewHeaderPublisher returns a TypedPublisher[Header] backed by CDR/XCDR1 encoding.
func NewHeaderPublisher(p dds.Participant, topic string, qos dds.QoS) (*dds.TypedPublisher[Header], error) {
	pub, err := p.NewPublisher(topic, qos)
	if err != nil {
		return nil, err
	}
	return dds.NewTypedPublisher[Header](pub, HeaderCodec{}), nil
}

// NewHeaderSubscriber returns a TypedSubscriber[Header] backed by CDR/XCDR1 decoding.
func NewHeaderSubscriber(p dds.Participant, topic string, qos dds.QoS, opts ...dds.SubscriberOption) (*dds.TypedSubscriber[Header], error) {
	sub, err := p.NewSubscriber(topic, qos, opts...)
	if err != nil {
		return nil, err
	}
	return dds.NewTypedSubscriber[Header](sub, HeaderCodec{}), nil
}

// Telemetry is generated from IDL struct Telemetry.
type Telemetry struct {
	Header      Header     `json:"header"`
	Values      [4]float64 `json:"values"`
	Temperature float32    `json:"temperature"`
	Valid       bool       `json:"valid"`
	Extras      []float64  `json:"extras"`
}

// TelemetryCodec encodes Telemetry values using CDR/XCDR1.
type TelemetryCodec struct{}

func (TelemetryCodec) Marshal(v Telemetry) ([]byte, error) {
	e := cdr.NewEncoder()
	e.WriteString(v.Header.TopicId)
	e.WriteInt64(v.Header.TimestampNs)
	e.WriteInt32(int32(v.Header.Priority))
	for _i := range v.Values {
		e.WriteFloat64(v.Values[_i])
	}
	e.WriteFloat32(v.Temperature)
	e.WriteBool(v.Valid)
	e.WriteUint32(uint32(len(v.Extras)))
	for _, _elem := range v.Extras {
		e.WriteFloat64(_elem)
	}
	return e.Bytes(), nil
}

func (TelemetryCodec) Unmarshal(data []byte) (Telemetry, error) {
	d, err := cdr.NewDecoder(data)
	if err != nil {
		return Telemetry{}, fmt.Errorf("TelemetryCodec: %w", err)
	}
	var v Telemetry
	if v.Header.TopicId, err = d.ReadString(); err != nil {
		return v, err
	}
	if v.Header.TimestampNs, err = d.ReadInt64(); err != nil {
		return v, err
	}
	{
		var _ev int32
		if _ev, err = d.ReadInt32(); err != nil {
			return v, err
		}
		v.Header.Priority = Priority(_ev)
	}
	for _i := range v.Values {
		if v.Values[_i], err = d.ReadFloat64(); err != nil {
			return v, err
		}
	}
	if v.Temperature, err = d.ReadFloat32(); err != nil {
		return v, err
	}
	if v.Valid, err = d.ReadBool(); err != nil {
		return v, err
	}
	{
		var _n uint32
		if _n, err = d.ReadUint32(); err != nil {
			return v, err
		}
		v.Extras = make([]float64, _n)
		for _i := range v.Extras {
			if v.Extras[_i], err = d.ReadFloat64(); err != nil {
				return v, err
			}
		}
	}
	return v, nil
}

// KeyFields returns the exported field names marked @key in the IDL source.
func (TelemetryCodec) KeyFields() []string {
	return nil
}

// NewTelemetryPublisher returns a TypedPublisher[Telemetry] backed by CDR/XCDR1 encoding.
func NewTelemetryPublisher(p dds.Participant, topic string, qos dds.QoS) (*dds.TypedPublisher[Telemetry], error) {
	pub, err := p.NewPublisher(topic, qos)
	if err != nil {
		return nil, err
	}
	return dds.NewTypedPublisher[Telemetry](pub, TelemetryCodec{}), nil
}

// NewTelemetrySubscriber returns a TypedSubscriber[Telemetry] backed by CDR/XCDR1 decoding.
func NewTelemetrySubscriber(p dds.Participant, topic string, qos dds.QoS, opts ...dds.SubscriberOption) (*dds.TypedSubscriber[Telemetry], error) {
	sub, err := p.NewSubscriber(topic, qos, opts...)
	if err != nil {
		return nil, err
	}
	return dds.NewTypedSubscriber[Telemetry](sub, TelemetryCodec{}), nil
}
