apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-dds-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-dds-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "go-dds-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.webhook.port }}
      targetPort: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-dds-operator.fullname" . }}-health
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-dds-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "go-dds-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.health.port }}
      targetPort: health
