// Copyright (c) 2026 Matt Jones. All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package idl

import (
	"fmt"
	"strings"
	"unicode"
)

// generator walks a Module tree and produces Go source.
type generator struct {
	root *Module
	sb   strings.Builder
}

func newGenerator(m *Module) *generator { return &generator{root: m} }

func (g *generator) generate() (string, error) {
	pkgName := g.packageName(g.root)
	g.line("// Code generated by go-DDS IDL compiler. DO NOT EDIT.")
	g.line("")
	g.line("package " + pkgName)
	g.line("")
	g.line(`import (`)
	g.line(`	"fmt"`)
	g.line("")
	g.line(`	dds "github.com/SoundMatt/go-DDS"`)
	g.line(`	"github.com/SoundMatt/go-DDS/cdr"`)
	g.line(`)`)
	g.line("")
	g.line(`// _ suppresses unused-import errors in modules with no structs.`)
	g.line(`var _ = fmt.Sprintf`)
	g.line(`var _ = dds.DefaultQoS`)
	g.line("")

	g.emitModule(g.root)
	return g.sb.String(), nil
}

func (g *generator) packageName(m *Module) string {
	if m.Name == "" {
		return "idlgen"
	}
	return strings.ToLower(m.Name)
}

func (g *generator) emitModule(m *Module) {
	for _, s := range m.Structs {
		g.emitStruct(s)
	}
	for _, sub := range m.Modules {
		// Sub-module structs are emitted in the same package for simplicity.
		g.emitModule(sub)
	}
}

func (g *generator) emitStruct(s Struct) {
	goName := toGoName(s.Name)
	g.line("// " + goName + " is generated from IDL struct " + s.Name + ".")
	g.line("type " + goName + " struct {")
	for _, f := range s.Fields {
		goFieldName := toGoName(f.Name)
		goType := g.goType(f.Type)
		jsonTag := strings.ToLower(camelToSnake(f.Name))
		g.line(fmt.Sprintf("\t%s %s `json:%q`", goFieldName, goType, jsonTag))
	}
	g.line("}")
	g.line("")
	g.emitCodec(s)
	g.emitFactories(s)
}

func (g *generator) emitFactories(s Struct) {
	goName := toGoName(s.Name)
	codecName := goName + "Codec"

	g.line("// New" + goName + "Publisher returns a TypedPublisher[" + goName + "] backed by CDR/XCDR1 encoding.")
	g.line("func New" + goName + "Publisher(p dds.Participant, topic string, qos dds.QoS) (*dds.TypedPublisher[" + goName + "], error) {")
	g.line("\tpub, err := p.NewPublisher(topic, qos)")
	g.line("\tif err != nil {")
	g.line("\t\treturn nil, err")
	g.line("\t}")
	g.line("\treturn dds.NewTypedPublisher[" + goName + "](pub, " + codecName + "{}), nil")
	g.line("}")
	g.line("")
	g.line("// New" + goName + "Subscriber returns a TypedSubscriber[" + goName + "] backed by CDR/XCDR1 decoding.")
	g.line("func New" + goName + "Subscriber(p dds.Participant, topic string, qos dds.QoS, opts ...dds.SubscriberOption) (*dds.TypedSubscriber[" + goName + "], error) {")
	g.line("\tsub, err := p.NewSubscriber(topic, qos, opts...)")
	g.line("\tif err != nil {")
	g.line("\t\treturn nil, err")
	g.line("\t}")
	g.line("\treturn dds.NewTypedSubscriber[" + goName + "](sub, " + codecName + "{}), nil")
	g.line("}")
	g.line("")
}

func (g *generator) emitCodec(s Struct) {
	goName := toGoName(s.Name)
	codecName := goName + "Codec"

	g.line("// " + codecName + " encodes " + goName + " values using CDR/XCDR1.")
	g.line("type " + codecName + " struct{}")
	g.line("")

	// Marshal
	g.line("func (" + codecName + ") Marshal(v " + goName + ") ([]byte, error) {")
	g.line("\te := cdr.NewEncoder()")
	for _, f := range s.Fields {
		g.line("\t" + g.encodeField(f))
	}
	g.line("\treturn e.Bytes(), nil")
	g.line("}")
	g.line("")

	// Unmarshal
	g.line("func (" + codecName + ") Unmarshal(data []byte) (" + goName + ", error) {")
	g.line("\td, err := cdr.NewDecoder(data)")
	g.line("\tif err != nil {")
	g.line("\t\treturn " + goName + "{}, fmt.Errorf(\"" + codecName + ": %w\", err)")
	g.line("\t}")
	g.line("\tvar v " + goName)
	for _, f := range s.Fields {
		g.line("\t" + g.decodeField(f))
	}
	g.line("\treturn v, nil")
	g.line("}")
	g.line("")
}

func (g *generator) goType(ts TypeSpec) string {
	switch ts.Kind {
	case KindBoolean:
		return "bool"
	case KindOctet:
		return "uint8"
	case KindShort:
		return "int16"
	case KindUShort:
		return "uint16"
	case KindLong:
		return "int32"
	case KindULong:
		return "uint32"
	case KindLongLong:
		return "int64"
	case KindULongLong:
		return "uint64"
	case KindFloat:
		return "float32"
	case KindDouble:
		return "float64"
	case KindString:
		return "string"
	case KindSequence:
		if ts.ElemType == nil {
			return "[]byte"
		}
		return "[]" + g.goType(*ts.ElemType)
	case KindStruct:
		return toGoName(ts.RefName)
	default:
		return "interface{}"
	}
}

func (g *generator) encodeField(f Field) string {
	fieldRef := "v." + toGoName(f.Name)
	return g.encodeExpr(f.Type, fieldRef)
}

func (g *generator) encodeExpr(ts TypeSpec, ref string) string {
	switch ts.Kind {
	case KindBoolean:
		return "e.WriteBool(" + ref + ")"
	case KindOctet:
		return "e.WriteUint8(" + ref + ")"
	case KindShort:
		return "e.WriteInt16(" + ref + ")"
	case KindUShort:
		return "e.WriteUint16(" + ref + ")"
	case KindLong:
		return "e.WriteInt32(" + ref + ")"
	case KindULong:
		return "e.WriteUint32(" + ref + ")"
	case KindLongLong:
		return "e.WriteInt64(" + ref + ")"
	case KindULongLong:
		return "e.WriteUint64(" + ref + ")"
	case KindFloat:
		return "e.WriteFloat32(" + ref + ")"
	case KindDouble:
		return "e.WriteFloat64(" + ref + ")"
	case KindString:
		return "e.WriteString(" + ref + ")"
	case KindSequence:
		if ts.ElemType != nil && ts.ElemType.Kind == KindOctet {
			return "e.WriteBytes(" + ref + ")"
		}
		// General sequence: write length then elements
		return fmt.Sprintf(
			"e.WriteUint32(uint32(len(%s))); for _, _elem := range %s { %s }",
			ref, ref, g.encodeExpr(*ts.ElemType, "_elem"),
		)
	case KindStruct:
		// Nested structs are inlined in CDR — no length prefix, no encapsulation
		// header. Recursively expand the referenced struct's fields at the call site.
		s := g.findStruct(ts.RefName)
		if s == nil {
			return "// TODO: encode " + ref + " (unknown struct " + ts.RefName + ")"
		}
		parts := make([]string, 0, len(s.Fields))
		for _, f := range s.Fields {
			parts = append(parts, g.encodeExpr(f.Type, ref+"."+toGoName(f.Name)))
		}
		return strings.Join(parts, "; ")
	default:
		return "// TODO: encode " + ref
	}
}

func (g *generator) decodeField(f Field) string {
	fieldRef := "v." + toGoName(f.Name)
	return g.decodeExpr(f.Type, fieldRef)
}

func (g *generator) decodeExpr(ts TypeSpec, dest string) string {
	switch ts.Kind {
	case KindBoolean:
		return fmt.Sprintf("if %s, err = d.ReadBool(); err != nil { return v, err }", dest)
	case KindOctet:
		return fmt.Sprintf("if %s, err = d.ReadUint8(); err != nil { return v, err }", dest)
	case KindShort:
		return fmt.Sprintf("if %s, err = d.ReadInt16(); err != nil { return v, err }", dest)
	case KindUShort:
		return fmt.Sprintf("if %s, err = d.ReadUint16(); err != nil { return v, err }", dest)
	case KindLong:
		return fmt.Sprintf("if %s, err = d.ReadInt32(); err != nil { return v, err }", dest)
	case KindULong:
		return fmt.Sprintf("if %s, err = d.ReadUint32(); err != nil { return v, err }", dest)
	case KindLongLong:
		return fmt.Sprintf("if %s, err = d.ReadInt64(); err != nil { return v, err }", dest)
	case KindULongLong:
		return fmt.Sprintf("if %s, err = d.ReadUint64(); err != nil { return v, err }", dest)
	case KindFloat:
		return fmt.Sprintf("if %s, err = d.ReadFloat32(); err != nil { return v, err }", dest)
	case KindDouble:
		return fmt.Sprintf("if %s, err = d.ReadFloat64(); err != nil { return v, err }", dest)
	case KindString:
		return fmt.Sprintf("if %s, err = d.ReadString(); err != nil { return v, err }", dest)
	case KindSequence:
		if ts.ElemType != nil && ts.ElemType.Kind == KindOctet {
			return fmt.Sprintf("if %s, err = d.ReadBytes(); err != nil { return v, err }", dest)
		}
		return fmt.Sprintf(
			"{ var _n uint32; if _n, err = d.ReadUint32(); err != nil { return v, err }; %s = make(%s, _n); for _i := range %s { %s } }",
			dest, g.goType(ts), dest, g.decodeExpr(*ts.ElemType, dest+"[_i]"),
		)
	case KindStruct:
		// Nested structs are inlined in CDR — expand the referenced struct's
		// fields at the call site, sharing the parent's decoder and err variable.
		s := g.findStruct(ts.RefName)
		if s == nil {
			return fmt.Sprintf("// TODO: decode %s (unknown struct %s)", dest, ts.RefName)
		}
		parts := make([]string, 0, len(s.Fields))
		for _, f := range s.Fields {
			parts = append(parts, g.decodeExpr(f.Type, dest+"."+toGoName(f.Name)))
		}
		return strings.Join(parts, "; ")
	default:
		return fmt.Sprintf("// TODO: decode %s", dest)
	}
}

func (g *generator) line(s string) {
	g.sb.WriteString(s)
	g.sb.WriteByte('\n')
}

// findStruct searches the module tree for a struct by its IDL name.
// Returns nil when the name is not defined in the current module.
func (g *generator) findStruct(name string) *Struct {
	return searchStruct(g.root, name)
}

func searchStruct(m *Module, name string) *Struct {
	for i := range m.Structs {
		if m.Structs[i].Name == name {
			return &m.Structs[i]
		}
	}
	for _, sub := range m.Modules {
		if s := searchStruct(sub, name); s != nil {
			return s
		}
	}
	return nil
}

// ── Name helpers ──────────────────────────────────────────────────────────────

// toGoName converts an IDL identifier to exported Go style (PascalCase).
// "vehicle_id" → "VehicleId", "speedKPH" → "SpeedKPH"
func toGoName(s string) string {
	parts := splitIdent(s)
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		r, size := []rune(p)[0], len([]byte(string([]rune(p)[:1])))
		b.WriteRune(unicode.ToUpper(r))
		_ = size
		b.WriteString(p[len(string([]rune{r})):])
	}
	return b.String()
}

// splitIdent splits an IDL identifier on underscores or camelCase boundaries.
func splitIdent(s string) []string {
	if strings.Contains(s, "_") {
		return strings.Split(s, "_")
	}
	// No underscores: treat as a single word
	return []string{s}
}

// camelToSnake converts camelCase or PascalCase to snake_case for JSON tags.
func camelToSnake(s string) string {
	// Replace underscores-based names directly
	if strings.Contains(s, "_") {
		return strings.ToLower(s)
	}
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}
